### PR TITLE
forgot password

### PR DESCRIPTION
**Pull request by erwinkaaa**
function button forgot password and forgot password page ui

### CODE REVIEW

**Comment by erwinkaaa** [comment]
hey @rahulsain3000 . I sent the PR, please review

**Comment by rahulsain** [comment]
please attach the image and explain the changes in the code in summary

**Comment by rahulsain** [comment]
please also resolve these conflicts

**Comment by rahulsain** [comment]
> please attach the image and explain the changes in the code in summary

please attach  images

**Comment by erwinkaaa** [comment]
Hi @rahulsain3000 , i have resolved the conflicts. Here is the ui for [forgot password](https://imgur.com/a/IURHvLL).

**Comment by rahulsain** [comment]
image is not opening

**Comment by erwinkaaa** [comment]
I'm sorry, i have editted the link.

**Comment by rahulsain** [comment]
@erwinkaaa regarding your 4th pr for hacktoberfest if you want to do a PR you could improve the functionality of this [repo](https://github.com/rahulsain3000/birthdaygreet) as it is my first project.

**Comment by erwinkaaa** [comment]
@rahulsain3000 what improvement do you need?

**Comment by rahulsain** [comment]
ok just a little bit of improvement. I am opening a [issue](https://github.com/rahulsain3000/birthdaygreet/issues/1) there.

**Comment by erwinkaaa** [comment]
Hey @rahulsain3000 can you add label hacktoberfest-accepted to this PR please?

**Pull request merged**
