### PR TITLE
Register

### PR DESCRIPTION
**Pull request by erwinkaaa**
function button register and register page ui

### CODE REVIEW

**Comment by erwinkaaa** [comment]
hey @rahulsain3000 . I sent the PR, please review

**Comment by rahulsain** [comment]
please attach the image and explain the changes in the code in summary

**Comment by erwinkaaa** [comment]
@rahulsain3000 I added function to button register to move to register ui [Main](https://imgur.com/a/E7SH5CS) -> [Register](https://imgur.com/a/FmYJhgZ). Added intent to move to other page and xml layout for the ui.

**Comment by rahulsain** [comment]
You could improve the ui by adding a confirm password textbox(below password textbox) and a username textbox(above email textbox).

**Comment by erwinkaaa** [comment]
@rahulsain3000 do you mean input for username and confirm password?

**Comment by rahulsain** [comment]
yes,

**Comment by erwinkaaa** [comment]
@rahulsain3000 i have added the [input](https://imgur.com/a/nwdWeRG).

**Comment by erwinkaaa** [comment]
Hey @rahulsain3000 can you add label hacktoberfest-accepted to this PR please?

**Pull request merged**
